services:
  cocoaromas-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cocoaromas-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
      DB_HOST: host.docker.internal
      DB_PORT: 1433
      DB_NAME: db_cocoaromas
      DB_USERNAME: sv_cocoaromas
      DB_PASSWORD: ApiUser123!
      DB_ENCRYPT: "false"
      JWT_EXPIRATION_SECONDS: 3600
      JWT_SECRET: YxSlAjcAJTCimmUlRynCCkWtXRVMm7uMmKtE8vPXqVi
      JWT_ISSUER: cocoaromas-api
    ports:
      - "8080:8080"
    restart: unless-stopped
