spring:
  application:
    name: cocoaromas-api
  profiles:
    default: local

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

security:
  jwt:
    secret: ${JWT_SECRET:YxSlAjcAJTCimmUlRynCCkWtXRVMm7uMmKtE8vPXqVi}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}
    issuer: ${JWT_ISSUER:cocoaromas-api}


app:
  stock:
    low-threshold: ${STOCK_LOW_THRESHOLD:5}
  flyway:
    auto-repair-on-validation-error: ${FLYWAY_AUTO_REPAIR_ON_VALIDATION_ERROR:false}
