CREATE TABLE users (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(120) NOT NULL,
    email NVARCHAR(120) NOT NULL UNIQUE,
    username NVARCHAR(80) NOT NULL UNIQUE,
    password_hash NVARCHAR(120) NOT NULL,
    role NVARCHAR(30) NOT NULL
);
